scss_files: 'stylesheets/**/*.css.scss'

exlude: 'stylesheets/vendors/**'

linters:
  Comment:
    enabled: false

  HexNotation:
    enabled: true
    style: uppercase # or 'lowercase'

  Indentation:
    enabled: true
    allow_non_nested_indentation: false
    character: space # or 'tab'
    width: 4

  PropertySortOrder:
    enabled: false
